import json, os, sys

base = os.path.join(os.path.dirname(__file__), '..', 'data', 'people')
base = os.path.abspath(base)

PEOPLE_RELATIONS = {
    "akutagawa": [
        {"id": "soseki", "name": "夏目漱石", "relation": "師", "note": "1916年、木曜会に参加。短編『鼻』を激賞され文壇に出た。"},
        {"name": "菊池寛", "relation": "盟友", "note": "第四次『新思潮』の同人。芥川賞の名の由来。"},
        {"name": "谷崎潤一郎", "relation": "論争相手・対立", "note": "『話のない小説』を巡る論争で対立。"},
        {"name": "久米正雄", "relation": "盟友"},
        {"name": "佐藤春夫", "relation": "盟友"},
        {"id": "dazai_osamu", "name": "太宰治", "relation": "崇拝する後輩"},
        {"name": "秀しげ子", "relation": "愛した人"},
    ],
    "aristotle": [
        {"id": "plato", "name": "プラトン", "relation": "師", "years": "前367-前347", "note": "17歳でアカデメイアに入門、20年間学んだ。"},
        {"id": "socrates", "name": "ソクラテス", "relation": "敬愛する先達"},
        {"name": "アレクサンドロス大王", "relation": "弟子", "years": "前343-"},
        {"name": "テオプラストス", "relation": "弟子・後継者"},
        {"name": "プラトンのイデア論", "relation": "批判", "note": "『イデアが個物と離れて存在することはありえない』と師の中心思想を批判。"},
    ],
    "bach": [
        {"id": "handel", "name": "ゲオルク・フリードリヒ・ヘンデル", "relation": "同時代のライバル", "note": "同年1685年生まれ。生涯一度も会わなかった。"},
        {"id": "mozart", "name": "モーツァルト", "relation": "後世の崇拝者"},
        {"id": "beethoven", "name": "ベートーヴェン", "relation": "讃えた後世", "note": "『バッハは小川ではなく大海だ』と讃えた。"},
        {"id": "mendelssohn", "name": "メンデルスゾーン", "relation": "再発見者", "note": "1829年に『マタイ受難曲』を復活蘇演。"},
        {"name": "アンナ・マグダレーナ・バッハ", "relation": "最愛の妻"},
        {"name": "カール・フィリップ・エマヌエル・バッハ", "relation": "息子・後継者"},
        {"name": "ブクステフーデ", "relation": "憧れの先達", "note": "1705年リューベックまで400km徒歩で聴きに行った。"},
    ],
    "bertrand_russell": [
        {"id": "wittgenstein", "name": "ウィトゲンシュタイン", "relation": "弟子・後に論敵"},
        {"name": "ホワイトヘッド", "relation": "共著者", "note": "『プリンキピア・マテマティカ』を10年かけて共著。"},
        {"name": "G.E.ムーア", "relation": "盟友"},
        {"id": "john_locke", "name": "ジョン・ロック", "relation": "敬愛する先達"},
        {"id": "einstein", "name": "アインシュタイン", "relation": "反核の同志", "note": "1955年『ラッセル＝アインシュタイン宣言』。"},
        {"name": "ヘーゲル哲学", "relation": "批判", "note": "若き日に心酔するも後に痛烈に批判、分析哲学へ転向。"},
    ],
    "bizet": [
        {"id": "berlioz", "name": "ベルリオーズ", "relation": "敬愛する先達"},
        {"id": "tchaikovsky", "name": "チャイコフスキー", "relation": "讃えた後世", "note": "『カルメンは10年後に最も人気のオペラになる』と予言。"},
        {"name": "シャルル・グノー", "relation": "師"},
        {"name": "アレヴィ", "relation": "師・義父"},
        {"name": "初演の批評家たち", "relation": "批判者", "note": "『カルメン』初演は酷評、3ヶ月後に失意のまま没した。"},
    ],
    "bruckner": [
        {"id": "wagner", "name": "ワーグナー", "relation": "崇拝する先達", "note": "1873年にバイロイトで会い、第3交響曲を献呈。"},
        {"id": "beethoven", "name": "ベートーヴェン", "relation": "敬愛する先達"},
        {"id": "mahler", "name": "マーラー", "relation": "後継者・弟子筋"},
        {"id": "brahms", "name": "ブラームス", "relation": "ライバル・不仲", "note": "ワーグナー派 vs ブラームス派の代理戦争の渦中に。"},
        {"name": "エドゥアルト・ハンスリック", "relation": "批判者", "note": "ウィーンの評論家。ブルックナー作品を執拗に酷評。"},
    ],
    "dante": [
        {"name": "ベアトリーチェ", "relation": "永遠の愛", "note": "9歳で一目惚れし、『神曲』天国篇の案内人。"},
        {"name": "ウェルギリウス", "relation": "敬愛する古代の師", "note": "『神曲』地獄篇・煉獄篇の案内人。"},
        {"name": "グイード・カヴァルカンティ", "relation": "盟友", "note": "『清新体』の同志、詩人。"},
        {"name": "トマス・アクィナス", "relation": "思想的影響"},
        {"name": "ボニファティウス8世", "relation": "宿敵", "note": "教皇の政治介入を憎悪、『神曲』地獄で聖職売買の罪に落とした。"},
        {"name": "ボッカッチョ", "relation": "後世の解説者"},
        {"name": "フィレンツェの黒派", "relation": "追放の敵", "note": "1302年に政争で祖国を追われた。"},
    ],
    "dazai_osamu": [
        {"id": "akutagawa", "name": "芥川龍之介", "relation": "崇拝する先達"},
        {"name": "井伏鱒二", "relation": "師", "note": "戦中戦後を支えた師。遺書に『井伏さんは悪人です』と書いた。"},
        {"name": "檀一雄", "relation": "盟友"},
        {"name": "坂口安吾", "relation": "盟友・無頼派"},
        {"name": "織田作之助", "relation": "盟友・無頼派"},
        {"name": "山崎富栄", "relation": "心中相手", "note": "1948年、玉川上水で入水心中。"},
        {"id": "kawabata", "name": "川端康成", "relation": "論敵・批判者", "note": "芥川賞選考で酷評され『刺す』と返書。生涯の確執。"},
    ],
    "debussy": [
        {"name": "エリック・サティ", "relation": "盟友"},
        {"id": "ravel", "name": "ラヴェル", "relation": "後進・後に疎遠"},
        {"name": "ステファヌ・マラルメ", "relation": "詩の共鳴", "note": "『牧神の午後』はマラルメの詩から。"},
        {"name": "モネ（印象派）", "relation": "美学の共鳴"},
        {"id": "wagner", "name": "ワーグナー", "relation": "若き日の心酔・後に批判"},
        {"name": "ガムラン音楽", "relation": "霊感の源", "note": "1889年パリ万博で衝撃を受けた。"},
    ],
    "descartes": [
        {"id": "plato", "name": "プラトン", "relation": "敬愛する先達"},
        {"name": "スコラ哲学", "relation": "批判", "note": "『全てを疑う』方法的懐疑でスコラ学を刷新。"},
        {"name": "クリスティーナ女王", "relation": "最晩年のパトロン", "note": "スウェーデンで朝5時の講義を命じられ、肺炎で没した。"},
        {"name": "メルセンヌ神父", "relation": "書簡の友"},
        {"id": "spinoza", "name": "スピノザ", "relation": "後世の継承者"},
        {"id": "kant", "name": "カント", "relation": "後世の批判者"},
    ],
    "einstein": [
        {"name": "ニールス・ボーア", "relation": "生涯の論敵", "note": "量子力学の解釈を巡る論争。『神はサイコロを振らない』。"},
        {"name": "マックス・プランク", "relation": "支援者・同志"},
        {"name": "シュレーディンガー", "relation": "同盟者"},
        {"name": "ミケーレ・ベッソ", "relation": "生涯の親友"},
        {"name": "ミレヴァ・マリッチ", "relation": "最初の妻"},
        {"name": "エルザ・アインシュタイン", "relation": "二度目の妻"},
        {"id": "bertrand_russell", "name": "バートランド・ラッセル", "relation": "反核の同志"},
        {"name": "ハイゼンベルク", "relation": "不確定性への批判"},
        {"name": "ナチス政権", "relation": "追われた体制", "note": "1933年ドイツを離れプリンストンへ。"},
    ],
    "goethe": [
        {"name": "フリードリヒ・シラー", "relation": "盟友", "years": "1794-1805"},
        {"id": "beethoven", "name": "ベートーヴェン", "relation": "文豪と音楽家の対面", "years": "1812"},
        {"id": "schubert", "name": "シューベルト", "relation": "歌曲の主題"},
        {"name": "クリスティアーネ・ヴルピウス", "relation": "妻"},
        {"name": "ナポレオン・ボナパルト", "relation": "敬意と複雑な関係", "years": "1808"},
        {"name": "ヘルダー", "relation": "師"},
    ],
    "handel": [
        {"id": "bach", "name": "バッハ", "relation": "同時代のライバル"},
        {"name": "ジョージ1世", "relation": "ロンドンの君主・パトロン"},
        {"name": "ブクステフーデ", "relation": "若き日の巡礼先"},
        {"id": "beethoven", "name": "ベートーヴェン", "relation": "讃えた後世"},
        {"name": "ボノンチーニ", "relation": "興行ライバル", "note": "ロンドンで激しい競争。"},
    ],
    "hijikata_toshizo": [
        {"id": "kondo_isami", "name": "近藤勇", "relation": "盟友・局長", "note": "天然理心流の同門。"},
        {"id": "okita_soji", "name": "沖田総司", "relation": "同志・弟分"},
        {"name": "永倉新八", "relation": "同志"},
        {"name": "斎藤一", "relation": "同志"},
        {"name": "山南敬助", "relation": "副長・切腹させた同志", "years": "1865"},
        {"name": "芹沢鴨", "relation": "排除した敵"},
        {"name": "榎本武揚", "relation": "函館政権の同志"},
        {"id": "sakamoto_ryoma", "name": "坂本龍馬", "relation": "敵対した志士"},
    ],
    "john_locke": [
        {"name": "シャフツベリ伯爵", "relation": "パトロン"},
        {"name": "ニュートン", "relation": "交友"},
        {"name": "デカルト", "relation": "批判的継承"},
        {"name": "ホッブズ", "relation": "論敵", "note": "『リヴァイアサン』の絶対主義を批判、抵抗権を主張。"},
        {"id": "bertrand_russell", "name": "ラッセル", "relation": "後世の継承者"},
        {"name": "アメリカ合衆国建国", "relation": "思想的父", "note": "独立宣言・合衆国憲法に影響。"},
    ],
    "kant": [
        {"id": "schopenhauer", "name": "ショーペンハウアー", "relation": "後継者"},
        {"name": "フィヒテ", "relation": "弟子・後継者"},
        {"name": "ヘーゲル", "relation": "後世の乗り越え者"},
        {"id": "kierkegaard", "name": "キェルケゴール", "relation": "後世の継承者"},
        {"name": "ヒューム", "relation": "覚醒者", "note": "『ヒュームが私を独断のまどろみから目覚めさせた』。"},
        {"name": "ルソー", "relation": "敬愛する思想家"},
    ],
    "kawabata": [
        {"id": "mishima_yukio", "name": "三島由紀夫", "relation": "弟子・後輩", "note": "文壇に推薦。三島自決の衝撃が晩年の自殺の一因とも。"},
        {"id": "akutagawa", "name": "芥川龍之介", "relation": "敬愛する先輩"},
        {"id": "dazai_osamu", "name": "太宰治", "relation": "対立した後輩"},
        {"name": "横光利一", "relation": "新感覚派の盟友"},
        {"name": "ノーベル文学賞", "relation": "日本人初受賞", "years": "1968"},
    ],
    "kierkegaard": [
        {"id": "kant", "name": "カント", "relation": "乗り越えるべき先達"},
        {"name": "ヘーゲル", "relation": "批判対象・論敵", "note": "体系化された弁証法を『実存』の名で痛烈に批判。"},
        {"name": "レギーネ・オルセン", "relation": "婚約破棄した恋人", "note": "その痛みが思想の原点に。"},
        {"name": "ソクラテス", "relation": "敬愛する古代の師"},
        {"name": "デンマーク国教会", "relation": "最晩年の批判対象"},
        {"id": "nietzsche", "name": "ニーチェ", "relation": "後世の同時代人"},
    ],
    "kondo_isami": [
        {"id": "hijikata_toshizo", "name": "土方歳三", "relation": "盟友・副長"},
        {"id": "okita_soji", "name": "沖田総司", "relation": "愛弟子・一番隊組長"},
        {"name": "永倉新八", "relation": "同志"},
        {"name": "芹沢鴨", "relation": "排除した敵", "years": "1863"},
        {"id": "sakamoto_ryoma", "name": "坂本龍馬", "relation": "対立する志士"},
        {"name": "勝海舟", "relation": "敬意ある敵方"},
        {"name": "新政府軍", "relation": "最後の敵", "years": "1868"},
    ],
    "mahler": [
        {"id": "bruckner", "name": "ブルックナー", "relation": "師筋・尊敬"},
        {"id": "beethoven", "name": "ベートーヴェン", "relation": "交響曲の先達"},
        {"id": "wagner", "name": "ワーグナー", "relation": "敬愛する先達"},
        {"name": "アルマ・マーラー", "relation": "妻"},
        {"id": "freud", "name": "フロイト", "relation": "精神分析を受けた先生", "years": "1910"},
        {"name": "ショーンベルク", "relation": "後継者・弟子筋"},
        {"name": "ウィーン宮廷歌劇場の反ユダヤ勢力", "relation": "追い出した敵"},
    ],
    "marcus_aurelius": [
        {"id": "seneca", "name": "セネカ", "relation": "敬愛する先達"},
        {"name": "エピクテトス", "relation": "思想的師"},
        {"name": "ルスティクス", "relation": "師"},
        {"name": "ピウス帝", "relation": "養父・皇帝の師"},
        {"name": "コンモドゥス", "relation": "失望した息子"},
        {"name": "ウェルス", "relation": "共同皇帝"},
    ],
    "matisse": [
        {"id": "picasso", "name": "ピカソ", "relation": "生涯のライバル", "note": "互いを『北極と南極』と呼び合った。"},
        {"name": "ギュスターヴ・モロー", "relation": "師"},
        {"name": "ドラン", "relation": "盟友"},
        {"id": "monet", "name": "モネ", "relation": "敬愛する先達"},
        {"name": "セザンヌ", "relation": "敬愛する先達"},
        {"name": "リディア・デレクトルスカヤ", "relation": "モデル・晩年の秘書"},
    ],
    "mishima_yukio": [
        {"id": "kawabata", "name": "川端康成", "relation": "師"},
        {"name": "太宰治", "relation": "公言した論敵", "note": "『太宰のような弱者の文学は嫌いだ』と面前で言った。"},
        {"name": "森田必勝", "relation": "楯の会の若き同志"},
        {"name": "石原慎太郎", "relation": "後輩作家・交友"},
        {"name": "美輪明宏", "relation": "友人"},
        {"name": "自衛隊", "relation": "決起を呼びかけた対象", "years": "1970"},
    ],
    "miyazawa_kenji": [
        {"name": "妹トシ", "relation": "最愛の妹", "note": "1922年に結核で急逝、『永訣の朝』に刻まれた。"},
        {"name": "父・政次郎", "relation": "宗旨を巡る対立"},
        {"name": "高村光太郎", "relation": "没後の理解者"},
        {"name": "法華経", "relation": "生涯の信仰"},
        {"name": "農民たち", "relation": "奉仕した隣人"},
    ],
    "monet": [
        {"name": "ルノワール", "relation": "生涯の親友"},
        {"name": "マネ", "relation": "先達・盟友"},
        {"name": "セザンヌ", "relation": "同志"},
        {"name": "ドガ", "relation": "印象派の同志・距離"},
        {"name": "カミーユ", "relation": "最初の妻・モデル"},
        {"name": "アリス・オシュデ", "relation": "二度目の妻"},
        {"id": "matisse", "name": "マティス", "relation": "後世の継承者"},
        {"name": "ジヴェルニーの庭", "relation": "生涯の主題"},
    ],
    "mozart": [
        {"id": "haydn", "name": "ハイドン", "relation": "敬愛する先達・友", "note": "ハイドンセット（弦楽四重奏曲6曲）を献呈。"},
        {"id": "beethoven", "name": "ベートーヴェン", "relation": "後世の巨匠"},
        {"name": "レオポルト・モーツァルト", "relation": "父・最初の師"},
        {"name": "ナンネル", "relation": "姉"},
        {"name": "コンスタンツェ", "relation": "妻"},
        {"name": "アロイジア・ヴェーバー", "relation": "若き日の片想い"},
        {"name": "サリエリ", "relation": "宮廷のライバル"},
        {"id": "bach", "name": "バッハ", "relation": "後に出会った先達"},
        {"name": "ヨーゼフ2世", "relation": "皇帝パトロン"},
    ],
    "nishida": [
        {"name": "鈴木大拙", "relation": "生涯の盟友", "note": "第四高等中学校の同級生。"},
        {"name": "田辺元", "relation": "弟子・後継者"},
        {"name": "ヘーゲル", "relation": "批判的継承"},
        {"name": "仏教思想", "relation": "思想的土台"},
        {"name": "西欧哲学", "relation": "対峙と融合"},
    ],
    "oda_nobunaga": [
        {"name": "豊臣秀吉", "relation": "家臣・後継者"},
        {"id": "tokugawa_ieyasu", "name": "徳川家康", "relation": "同盟者"},
        {"name": "明智光秀", "relation": "裏切った家臣", "years": "1582", "note": "本能寺の変で信長を討った。"},
        {"name": "今川義元", "relation": "倒した敵", "years": "1560"},
        {"name": "武田信玄", "relation": "宿敵"},
        {"name": "武田勝頼", "relation": "倒した宿敵", "years": "1575"},
        {"name": "比叡山延暦寺", "relation": "焼き討ちした宗教的対立", "years": "1571"},
        {"name": "ルイス・フロイス", "relation": "評価された宣教師"},
    ],
    "okita_soji": [
        {"id": "kondo_isami", "name": "近藤勇", "relation": "師・局長"},
        {"id": "hijikata_toshizo", "name": "土方歳三", "relation": "副長・兄貴分"},
        {"name": "永倉新八", "relation": "同志"},
        {"name": "斎藤一", "relation": "同志"},
        {"name": "結核", "relation": "早世の病", "years": "1868"},
    ],
    "oscar_wilde": [
        {"name": "アルフレッド・ダグラス卿", "relation": "恋人・破滅の原因"},
        {"name": "クインズベリー侯爵", "relation": "宿敵"},
        {"name": "コンスタンス・ワイルド", "relation": "妻"},
        {"name": "ジョージ・バーナード・ショー", "relation": "同時代の論敵・批評家"},
        {"name": "ジョン・ラスキン", "relation": "オックスフォード時代の師"},
        {"name": "ウォルター・ペイター", "relation": "唯美主義の師"},
    ],
    "paganini": [
        {"id": "liszt", "name": "リスト", "relation": "讃えた後世"},
        {"id": "berlioz", "name": "ベルリオーズ", "relation": "作品の委嘱者"},
        {"id": "brahms", "name": "ブラームス", "relation": "後世の継承者"},
        {"id": "rachmaninoff", "name": "ラフマニノフ", "relation": "後世の継承者"},
        {"name": "悪魔との契約の噂", "relation": "生涯ついて回った中傷"},
    ],
    "picasso": [
        {"id": "matisse", "name": "マティス", "relation": "生涯のライバル・友"},
        {"name": "ジョルジュ・ブラック", "relation": "盟友", "note": "キュビスムを二人で開いた。"},
        {"name": "セザンヌ", "relation": "敬愛する先達"},
        {"name": "オルガ・コクローヴァ", "relation": "最初の妻"},
        {"name": "ドラ・マール", "relation": "愛人・モデル"},
        {"name": "フランソワーズ・ジロー", "relation": "愛人・母"},
        {"name": "ジャクリーヌ・ロック", "relation": "二度目の妻"},
        {"name": "フランコ政権", "relation": "政治的敵"},
    ],
    "raphael": [
        {"id": "leonardo", "name": "レオナルド・ダ・ヴィンチ", "relation": "敬愛する先達"},
        {"id": "michelangelo", "name": "ミケランジェロ", "relation": "ライバル"},
        {"name": "ペルジーノ", "relation": "師"},
        {"name": "教皇ユリウス2世", "relation": "パトロン"},
        {"name": "教皇レオ10世", "relation": "パトロン・友人"},
        {"name": "マルガリータ", "relation": "愛した女性・モデル"},
    ],
    "ravel": [
        {"id": "debussy", "name": "ドビュッシー", "relation": "先達・後に距離"},
        {"name": "エリック・サティ", "relation": "敬愛する先達"},
        {"name": "ガブリエル・フォーレ", "relation": "師"},
        {"id": "stravinsky", "name": "ストラヴィンスキー", "relation": "交友"},
        {"name": "ディアギレフ", "relation": "バレエ・リュスの依頼主"},
        {"name": "パリ音楽院", "relation": "不公平を受けた学校", "note": "ローマ賞に5度挑戦するも受賞できず。"},
    ],
    "rembrandt": [
        {"name": "ピーテル・ラストマン", "relation": "師"},
        {"name": "サスキア", "relation": "最初の妻・モデル"},
        {"name": "ヘンドリッキエ・ストッフェルス", "relation": "内縁の妻・晩年の伴侶"},
        {"name": "アムステルダム市民", "relation": "破産で訣別した顧客"},
        {"name": "ウィーレンブルフ家", "relation": "富裕パトロン"},
        {"name": "聖書", "relation": "生涯の主題"},
    ],
    "rodin": [
        {"name": "カミーユ・クローデル", "relation": "愛人・弟子"},
        {"name": "ローズ・ブーレ", "relation": "生涯の伴侶"},
        {"name": "カリエール", "relation": "盟友"},
        {"name": "ブルーデル", "relation": "弟子"},
        {"name": "リルケ", "relation": "秘書・詩人"},
        {"name": "文芸協会", "relation": "拒絶された依頼主", "note": "『バルザック像』が酷評され受領拒否。"},
    ],
    "saigo_takamori": [
        {"name": "大久保利通", "relation": "盟友から宿敵へ"},
        {"name": "勝海舟", "relation": "江戸無血開城の盟友", "years": "1868"},
        {"name": "島津斉彬", "relation": "師・主君"},
        {"id": "sakamoto_ryoma", "name": "坂本龍馬", "relation": "盟友"},
        {"name": "桐野利秋", "relation": "腹心"},
        {"name": "明治政府", "relation": "決起の相手", "years": "1877"},
    ],
    "sakamoto_ryoma": [
        {"id": "saigo_takamori", "name": "西郷隆盛", "relation": "薩長同盟の同志", "years": "1866"},
        {"name": "桂小五郎", "relation": "長州代表の同志"},
        {"name": "勝海舟", "relation": "師・恩人"},
        {"name": "中岡慎太郎", "relation": "盟友"},
        {"name": "千葉佐那", "relation": "婚約した女剣士"},
        {"name": "お龍", "relation": "妻"},
        {"id": "kondo_isami", "name": "近藤勇", "relation": "敵対する幕府方"},
        {"name": "見廻組", "relation": "暗殺者", "years": "1867"},
    ],
    "satie": [
        {"id": "debussy", "name": "ドビュッシー", "relation": "盟友"},
        {"id": "ravel", "name": "ラヴェル", "relation": "後世の継承者"},
        {"name": "ジャン・コクトー", "relation": "盟友"},
        {"id": "picasso", "name": "ピカソ", "relation": "『パラード』の共同制作者"},
        {"name": "六人組", "relation": "影響を与えた後進"},
        {"name": "シュザンヌ・ヴァラドン", "relation": "短い恋人"},
    ],
    "schopenhauer": [
        {"id": "kant", "name": "カント", "relation": "師と仰いだ先達"},
        {"name": "ヘーゲル", "relation": "憎悪した同時代の敵", "note": "同じベルリン大学で同時刻に講義を開くも、学生は全員ヘーゲルに流れた生涯の屈辱。"},
        {"name": "仏教・ウパニシャッド", "relation": "東洋思想の継承"},
        {"id": "nietzsche", "name": "ニーチェ", "relation": "後世の愛読者"},
        {"id": "wagner", "name": "ワーグナー", "relation": "影響を与えた後進"},
        {"name": "母・ヨハンナ", "relation": "不仲の肉親"},
    ],
    "schubert": [
        {"id": "beethoven", "name": "ベートーヴェン", "relation": "神格化した先達", "note": "1827年の葬儀で棺を担ぎ、翌年自身もベートーヴェンの隣に埋葬された。"},
        {"id": "goethe", "name": "ゲーテ", "relation": "歌曲の原点"},
        {"name": "サリエリ", "relation": "師"},
        {"name": "シュパウン", "relation": "学友・生涯の友"},
        {"name": "フォーゲル", "relation": "歌手・音楽仲間"},
        {"id": "schumann", "name": "シューマン", "relation": "没後の再発見者", "note": "交響曲『ザ・グレート』を発見。"},
    ],
    "seaborg": [
        {"name": "アーネスト・ローレンス", "relation": "バークレーの師・同僚"},
        {"name": "エンリコ・フェルミ", "relation": "マンハッタン計画の同僚"},
        {"name": "オッペンハイマー", "relation": "マンハッタン計画の指導者"},
        {"name": "ケネディ大統領", "relation": "原子力委員会委員長の任命者"},
    ],
    "seneca": [
        {"name": "ネロ帝", "relation": "弟子・後に死を命じた暴君", "note": "幼少期の家庭教師だったが、反逆疑惑で自害を命じられた。"},
        {"name": "エピクテトス", "relation": "ストア哲学の後進"},
        {"id": "marcus_aurelius", "name": "マルクス・アウレリウス", "relation": "後世の継承者"},
        {"name": "パウリナ", "relation": "妻"},
        {"name": "カリグラ帝", "relation": "迫害者"},
        {"name": "クラウディウス帝", "relation": "追放者"},
    ],
    "shakespeare": [
        {"name": "クリストファー・マーロウ", "relation": "同時代のライバル・先輩"},
        {"name": "ベン・ジョンソン", "relation": "盟友・後輩"},
        {"name": "アン・ハサウェイ", "relation": "妻"},
        {"name": "サウサンプトン伯爵", "relation": "パトロン"},
        {"name": "グローブ座", "relation": "生涯の舞台"},
        {"name": "エリザベス1世", "relation": "女王パトロン"},
    ],
    "shostakovich": [
        {"name": "スターリン", "relation": "恐怖の支配者", "note": "プラウダで激しく批判され、生涯処刑の恐怖と共に作曲した。"},
        {"id": "prokofiev", "name": "プロコフィエフ", "relation": "同時代のソ連作曲家"},
        {"id": "stravinsky", "name": "ストラヴィンスキー", "relation": "亡命先の同胞"},
        {"id": "mahler", "name": "マーラー", "relation": "敬愛する先達"},
        {"name": "ジダーノフ批判", "relation": "公の糾弾", "years": "1948"},
        {"name": "ムラヴィンスキー", "relation": "盟友の指揮者"},
    ],
    "stravinsky": [
        {"name": "リムスキー＝コルサコフ", "relation": "師"},
        {"name": "ディアギレフ", "relation": "バレエ・リュスの委嘱者"},
        {"id": "ravel", "name": "ラヴェル", "relation": "交友"},
        {"id": "debussy", "name": "ドビュッシー", "relation": "敬愛する先達"},
        {"name": "バランシン", "relation": "振付の盟友"},
        {"name": "パリの聴衆", "relation": "『春の祭典』暴動の相手", "years": "1913"},
        {"id": "shostakovich", "name": "ショスタコーヴィチ", "relation": "祖国の後輩"},
    ],
    "takemitsu": [
        {"name": "黛敏郎", "relation": "盟友"},
        {"name": "早坂文雄", "relation": "師"},
        {"name": "ジョン・ケージ", "relation": "友人・影響"},
        {"name": "オリヴィエ・メシアン", "relation": "敬愛する先達"},
        {"name": "黒澤明", "relation": "映画音楽の共同制作者"},
        {"name": "岩城宏之", "relation": "指揮者・盟友"},
    ],
    "tchaikovsky": [
        {"name": "アントン・ルビンシテイン", "relation": "師"},
        {"name": "ニコライ・ルビンシテイン", "relation": "恩人・友"},
        {"name": "フォン・メック夫人", "relation": "生涯のパトロン・文通相手", "note": "14年間月給を送ったが、生涯会わなかった。"},
        {"id": "brahms", "name": "ブラームス", "relation": "苦手な同時代人"},
        {"id": "bizet", "name": "ビゼー", "relation": "讃えた先達"},
        {"id": "rachmaninoff", "name": "ラフマニノフ", "relation": "後継者"},
        {"name": "アントニーナ", "relation": "失敗した妻", "note": "形式的結婚、数週間で破綻し自殺未遂。"},
    ],
    "voltaire": [
        {"name": "フリードリヒ大王", "relation": "パトロン・後に決裂"},
        {"name": "ルソー", "relation": "論敵"},
        {"name": "ルイ15世", "relation": "批判対象の王"},
        {"name": "カトリック教会", "relation": "生涯の批判対象"},
        {"name": "エミリー・デュ・シャトレ夫人", "relation": "愛人・知的伴侶"},
        {"name": "ライプニッツ", "relation": "楽観主義を嘲笑した相手"},
    ],
}

updated = []
for pid, rels in PEOPLE_RELATIONS.items():
    fp = os.path.join(base, pid + '.json')
    if not os.path.exists(fp):
        print('missing:', pid); continue
    with open(fp, 'r', encoding='utf-8') as f:
        data = json.load(f)
    data['relations'] = rels
    with open(fp, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    updated.append((pid, len(rels)))

print(f'Updated {len(updated)} people')
BLOCK_KW = ['宿敵','敵','ライバル','対立','裏切','論敵','抗争','競争','暗殺','刺客','暗殺者','抗命','反発','確執','不仲','宗教的対立','批判者','批判']
tot_f = tot_b = 0
for p, n in updated:
    fp = os.path.join(base, p + '.json')
    with open(fp, 'r', encoding='utf-8') as f:
        d = json.load(f)
    b = sum(1 for r in d['relations'] if any(kw in (r.get('relation','')+r.get('note','')) for kw in BLOCK_KW))
    tot_f += (n - b); tot_b += b
print(f'Total: {tot_f} follow / {tot_b} block')
